apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 0.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: http-service
spec:
  type: NodePort
  selector:
    app: apache
  ports:
  - port: 8080
    targetPort: 80
